title: 游戏列表
description: 精选网页游戏合集
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

lang: zh-CN
permalink: /:categories/:title/
timezone: Asia/Shanghai

# 导航菜单
navigation:
  - title: 首页
    url: /
  - title: 游戏分类
    url: /categories/
  - title: 关于我们
    url: /about/

# 网站设置
url: "https://chengkeshuai.github.io"
baseurl: ""
show_downloads: false
google_analytics: # 如果有Google Analytics ID可以填在这里

# 社交链接
github_username: chengkeshuai

# 自定义设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
      comments: true

comments:
  provider: giscus
  giscus:
    repo: chengkeshuai/chengkeshuai.github.io
    repo-id: # 稍后填写
    category: Announcements
    category-id: # 稍后填写
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    theme: light