title: 游戏列表
description: 精选网页游戏合集
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

lang: zh-CN
permalink: /:categories/:title/
timezone: Asia/Shanghai

# 导航菜单
navigation:
  - title: 首页
    url: /
  - title: 游戏分类
    url: /categories/
  - title: 关于我们
    url: /about/

# 网站设置
url: "https://chengkeshuai.github.io"
baseurl: ""

# 社交链接
github_username: chengkeshuai